### PR TITLE
Fix Stepper SSR issues

### LINKED ISSUE #656: hydration error stepper component nextjs 13 app dir
**Describe the bug** A clear and concise description of what the bug is.

When using the `app` dir in nextjs 13 there is a console error using Stepper component

```
Warning: Expected server HTML to contain a matching <animate> in <path>.
    at animate
    at path
    at g
    at svg
    at u (webpack-internal:///(app-client)/./node_modules/@telefonica/mistica/dist-es/icons/icon-success.js:81:17)
    at O (webpack-internal:///(app-client)/./node_modules/@telefonica/mistica/dist-es/icons/icon-success.js:114:17)
    at div
    at div
    at div
    at Z (webpack-internal:///(app-client)/./node_modules/@telefonica/mistica/dist-es/stepper.js:82:18)
    at div
    at CustomStepper (webpack-internal:///(app-client)/./src/components/wizards/custom-stepper.tsx:7:11)
    at ScrollAndFocusHandler (webpack-internal:///(app-client)/./node_modules/next/dist/client/components/layout-router.js:149:1)
    at InnerLayoutRouter (webpack-internal:///(app-client)/./node_modules/next/dist/client/components/layout-router.js:178:11)
    at RedirectErrorBoundary (webpack-internal:///(app-client)/./node_modules/next/dist/client/components/layout-router.js:334:9)
    at RedirectBoundary (webpack-internal:///(app-client)/./node_modules/next/dist/client/components/layout-router.js:341:11)
    at NotFoundBoundary (webpack-internal:///(app-client)/./node_modules/next/dist/client/components/layout-router.js:377:11)
    at LoadingBoundary (webpack-internal:///(app-client)/./node_modules/next/dist/client/components/layout-router.js:289:11)
    at ErrorBoundary (webpack-internal:///(app-client)/./node_modules/next/dist/client/components/error-boundary.js:76:11)
    at RenderFromTemplateContext (webpack-internal:///(app-client)/./node_modules/next/dist/client/components/render-from-template-context.js:12:34)
    at OuterLayoutRouter (webpack-internal:///(app-client)/./node_modules/next/dist/client/components/layout-router.js:20:11)
    at ScrollAndFocusHandler (webpack-internal:///(app-client)/./node_modules/next/dist/client/components/layout-router.js:149:1)
    at InnerLayoutRouter (webpack-internal:///(app-client)/./node_modules/next/dist/client/components/layout-router.js:178:11)
    at RedirectErrorBoundary (webpack-internal:///(app-client)/./node_modules/next/dist/client/components/layout-router.js:334:9)
    at RedirectBoundary (webpack-internal:///(app-client)/./node_modules/next/dist/client/components/layout-router.js:341:11)
    at NotFoundBoundary (webpack-internal:///(app-client)/./node_modules/next/dist/client/components/layout-router.js:377:11)
    at LoadingBoundary (webpack-internal:///(app-client)/./node_modules/next/dist/client/components/layout-router.js:289:11)
    at ErrorBoundary (webpack-internal:///(app-client)/./node_modules/next/dist/client/components/error-boundary.js:76:11)
    at RenderFromTemplateContext (webpack-internal:///(app-client)/./node_modules/next/dist/client/components/render-from-template-context.js:12:34)
    at OuterLayoutRouter (webpack-internal:///(app-client)/./node_modules/next/dist/client/components/layout-router.js:20:11)
    at ScrollAndFocusHandler (webpack-internal:///(app-client)/./node_modules/next/dist/client/components/layout-router.js:149:1)
    at InnerLayoutRouter (webpack-internal:///(app-client)/./node_modules/next/dist/client/components/layout-router.js:178:11)
    at RedirectErrorBoundary (webpack-internal:///(app-client)/./node_modules/next/dist/client/components/layout-router.js:334:9)
    at RedirectBoundary (webpack-internal:///(app-client)/./node_modules/next/dist/client/components/layout-router.js:341:11)
    at NotFoundErrorBoundary (webpack-internal:///(app-client)/./node_modules/next/dist/client/components/layout-router.js:370:9)
    at NotFoundBoundary (webpack-internal:///(app-client)/./node_modules/next/dist/client/components/layout-router.js:377:11)
    at LoadingBoundary (webpack-internal:///(app-client)/./node_modules/next/dist/client/components/layout-router.js:289:11)
    at ErrorBoundary (webpack-internal:///(app-client)/./node_modules/next/dist/client/components/error-boundary.js:76:11)
    at RenderFromTemplateContext (webpack-internal:///(app-client)/./node_modules/next/dist/client/components/render-from-template-context.js:12:34)
    at OuterLayoutRouter (webpack-internal:///(app-client)/./node_modules/next/dist/client/components/layout-router.js:20:11)
    at div
    at div
    at Me (webpack-internal:///(app-client)/./node_modules/@telefonica/mistica/dist-es/dialog.js:406:9)
    at P (webpack-internal:///(app-client)/./node_modules/@telefonica/mistica/dist-es/screen-size-context-provider.js:17:21)
    at E (webpack-internal:///(app-client)/./node_modules/@telefonica/mistica/dist-es/utils/document-visibility.js:16:19)
    at W (webpack-internal:///(app-client)/./node_modules/@telefonica/mistica/dist-es/utils/aspect-ratio-support.js:74:21)
    at p (webpack-internal:///(app-client)/./node_modules/@telefonica/mistica/dist-es/utils/analytics.js:23:21)
    at S (webpack-internal:///(app-client)/./node_modules/@telefonica/mistica/dist-es/modal-context-provider.js:43:21)
    at w (webpack-internal:///(app-client)/./node_modules/@telefonica/mistica/dist-es/tab-focus.js:21:21)
    at ut (webpack-internal:///(app-client)/./node_modules/@telefonica/mistica/dist-es/theme-context-provider.js:100:18)
    at MisticaProvider (webpack-internal:///(app-client)/./src/contexts/mistica-context-provider.tsx:11:11)
    at WalletContextProvider (webpack-internal:///(app-client)/./src/contexts/wallet-context.tsx:58:11)
    at GoogleAnalyticsContextProvider (webpack-internal:///(app-client)/./src/contexts/google-analytics-context.tsx:45:11)
    at body
    at html
    at ScrollAndFocusHandler (webpack-internal:///(app-client)/./node_modules/next/dist/client/components/layout-router.js:149:1)
    at InnerLayoutRouter (webpack-internal:///(app-client)/./node_modules/next/dist/client/components/layout-router.js:178:11)
    at RedirectErrorBoundary (webpack-internal:///(app-client)/./node_modules/next/dist/client/components/layout-router.js:334:9)
    at RedirectBoundary (webpack-internal:///(app-client)/./node_modules/next/dist/client/components/layout-router.js:341:11)
    at NotFoundBoundary (webpack-internal:///(app-client)/./node_modules/next/dist/client/components/layout-router.js:377:11)
    at LoadingBoundary (webpack-internal:///(app-client)/./node_modules/next/dist/client/components/layout-router.js:289:11)
    at ErrorBoundaryHandler (webpack-internal:///(app-client)/./node_modules/next/dist/client/components/error-boundary.js:63:9)
    at ErrorBoundary (webpack-internal:///(app-client)/./node_modules/next/dist/client/components/error-boundary.js:76:11)
    at RenderFromTemplateContext (webpack-internal:///(app-client)/./node_modules/next/dist/client/components/render-from-template-context.js:12:34)
    at OuterLayoutRouter (webpack-internal:///(app-client)/./node_modules/next/dist/client/components/layout-router.js:20:11)
    at ReactDevOverlay (webpack-internal:///(app-client)/./node_modules/next/dist/client/components/react-dev-overlay/internal/ReactDevOverlay.js:58:9)
    at HotReload (webpack-internal:///(app-client)/./node_modules/next/dist/client/components/react-dev-overlay/hot-reloader-client.js:19:11)
    at Router (webpack-internal:///(app-client)/./node_modules/next/dist/client/components/app-router.js:99:11)
    at ErrorBoundaryHandler (webpack-internal:///(app-client)/./node_modules/next/dist/client/components/error-boundary.js:63:9)
    at ErrorBoundary (webpack-internal:///(app-client)/./node_modules/next/dist/client/components/error-boundary.js:76:11)
    at AppRouter (webpack-internal:///(app-client)/./node_modules/next/dist/client/components/app-router.js:20:13)
    at ServerRoot (webpack-internal:///(app-client)/./node_modules/next/dist/client/app-index.js:126:11)
    at RSCComponent
    at Root (webpack-internal:///(app-client)/./node_modules/next/dist/client/app-index.js:143:11)

```

```
Warning: You are accessing "digest" from the errorInfo object passed to onRecoverableError. This property is deprecated and will be removed in a future version of React. To access the digest of an Error look for this property on the Error instance itself.
```

```
Uncaught Error: There was an error while hydrating. Because the error happened outside of a Suspense boundary, the entire root will switch to client rendering.
    at updateHostRoot (webpack-internal:///(:3000/es/login/app-client)/./node_modules/next/dist/compiled/react-dom/cjs/react-dom.development.js:22943:57)
    at beginWork (webpack-internal:///(:3000/es/login/app-client)/./node_modules/next/dist/compiled/react-dom/cjs/react-dom.development.js:24809:14)
    at beginWork$1 (webpack-internal:///(:3000/es/login/app-client)/./node_modules/next/dist/compiled/react-dom/cjs/react-dom.development.js:32180:14)
    at performUnitOfWork (webpack-internal:///(:3000/es/login/app-client)/./node_modules/next/dist/compiled/react-dom/cjs/react-dom.development.js:31077:12)
    at workLoopSync (webpack-internal:///(:3000/es/login/app-client)/./node_modules/next/dist/compiled/react-dom/cjs/react-dom.development.js:30886:5)
    at renderRootSync (webpack-internal:///(:3000/es/login/app-client)/./node_modules/next/dist/compiled/react-dom/cjs/react-dom.development.js:30851:7)
    at recoverFromConcurrentError (webpack-internal:///(:3000/es/login/app-client)/./node_modules/next/dist/compiled/react-dom/cjs/react-dom.development.js:30104:20)
    at performConcurrentWorkOnRoot (webpack-internal:///(:3000/es/login/app-client)/./node_modules/next/dist/compiled/react-dom/cjs/react-dom.development.js:29991:22)
    at workLoop (webpack-internal:///(:3000/es/login/app-client)/./node_modules/next/dist/compiled/scheduler/index.js:11:3897)
    at flushWork (webpack-internal:///(:3000/es/login/app-client)/./node_modules/next/dist/compiled/scheduler/index.js:11:3606)
    at MessagePort.performWorkUntilDeadline (webpack-internal:///(:3000/es/login/app-client)/./node_modules/next/dist/compiled/scheduler/index.js:11:1787)
```

**To Reproduce** Steps to reproduce the behavior:

Create the following component
```
'use client';

import {Stepper} from '@telefonica/mistica';

type Props = {
    step?: number;
    textValues?: string[];
};

const CustomStepper = ({step, textValues}: Props) => {
    return (
        <div className="h-[100px]">
            <Stepper currentIndex={1} steps={['Hola', 'Adiós']} aria-label="Progress" />
        </div>
    );
};

export default CustomStepper;
```

and use it in a page like the following
```
const Page = ({params, searchParams}: LayoutPagesProps) => {
   
    return (
        <>
            <CustomStepper />
        </>
    );
};
```

Passing `currentIndex={0}` as Stepper component prop does not throw any console error

### PR DESCRIPTION
**Pull request by sergivillar**
Fixes #656

### CODE REVIEW

File: src/feedback.tsx [hunk 1]
```diff
@@ -299,13 +299,20 @@ export const FeedbackScreen: React.FC<FeedbackScreenProps> = ({
 export const SuccessFeedbackScreen: React.FC<AssetFeedbackProps> = ({dataAttributes, ...props}) => {
     const {isTabletOrSmaller} = useScreenSize();
     const {skinName} = useTheme();
+    const isFirstRender = useIsFirstRender();
```
Comment (atabel) [inline src/feedback.tsx:302]: does it make sense to include  this logic inside the IconSuccess?

Comment (sergivillar) [reply src/feedback.tsx:302]: mmm maybe? I added it this way as we already have a skipAnimation prop with other conditions in the stepper, also we have another icons that need this... but I think it make sense to disable this animations for those icons , I can make that changes

File: src/hooks.tsx [hunk 2]
```diff
@@ -217,3 +217,15 @@ export const useIsInViewport = (
 
     return isInViewport;
 };
+
+export const useIsFirstRender = (): boolean => {
```
Comment (atabel) [inline src/hooks.tsx:221]: you should use an state + effect, otherwise there won't be a re-render.
Something like this:
https://beta.reactjs.org/reference/react-dom/client/hydrateRoot#handling-different-client-and-server-content

Comment (sergivillar) [reply src/hooks.tsx:221]: mmm in this case, do we want that behaviour here? `useIsFirstRender` is this case, is we want to force a re-render, maybe we need a new name? any idea?

also, we want to force a re-render for this animation? in the case of the stepper, that animation will take place once yo go to next/prev state, so no need of that state + effect, I have doubts in adding that state + effect in the case of the icons,... WDYT?

**Review by atabel — APPROVED** [review]
