### PR TITLE
chore(Tabs): fix broken story in dev

### LINKED ISSUE #649: Tabs story page doesn't work in local environment
**Describe the bug** 

In storybook we have a strange behavior in Tabs story page when you access in your local environment. Your tab will be frozen and you have to close it. This is happening with something related with the prop icon (in prop tabs) that is a React.ReactNode, when you pass a null in this prop or no pass any values, the story works as usual.

**To Reproduce** 

1. Uncomment lines in tab story related with Icon logic.
2. Run storybook in you local environment
3. Navigate to http://localhost:6006/?path=/story/components-tabs--default
4. Your browser tab will be frozen and you have to close it

**Expected behavior** 
Tabs story works as usual with Icons example.

### PR DESCRIPTION
**Pull request by atabel**
fixes #649

### CODE REVIEW

File: src/__stories__/tabs-story.tsx [hunk 1]
```diff
@@ -8,29 +8,33 @@ export default {
...
                 text,
-                // TODO: #649 Bug with this prop in local environment
-                // icon: withIcon ? <IconCloseRegular size={pxToRem(24)} color="currentColor" /> : null,
             }))}
         />
     );
 };
-
 Default.storyName = 'Tabs';
-Default.args = {
```
Comment (atabel) [inline src/__stories__/tabs-story.tsx:32]: for some reason, this story breaks when using the args addon
